name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v4

    - name: Node.js kur
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Ortam Değişkenlerini Ayarla
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: echo "Secrets yüklendi."

    - name: Bağımlılıkları yükle
      run: npm install

    - name: Build aşaması
      run: npm run build
